name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd ~/devops-assignment/app
            git pull origin main

            sudo docker build -t devops-app .

            sudo docker stop devops-app || true
            sudo docker rm devops-app || true

            sudo docker run -d \
              --name devops-app \
              -p 3000:3000 \
              --restart unless-stopped \
              devops-app
